# Workflow name - this is just a label for your workflow
name: portfolio

# Define the event that triggers this workflow
on:
  push: # This workflow runs whenever there's a push event
    branches: 
      - main # Only triggers when changes are pushed to the 'main' branch

# Define the jobs for this workflow
jobs:
  build:
    # Specify the type of runner to execute the job
    runs-on: ubuntu-latest # Use the latest version of the Ubuntu operating system for the runner

    # Steps define the sequence of tasks to perform in the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code # Descriptive name for the step
        uses: actions/checkout@v3 # Action to clone the repository code into the runner

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials # Descriptive name for the step
        uses: aws-actions/configure-aws-credentials@v2 # AWS action to set up credentials
        with: # Provide input variables to the action
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Access key ID, securely stored in GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Secret access key, securely stored in GitHub secrets
          aws-region: ap-south-1 # AWS region where the resources are located (e.g., S3 bucket)

      # Step 3: Sync files to an S3 bucket
      - name: Deploy static site to S3 bucket # Descriptive name for the step
        run: aws s3 sync . s3://portfolio-website --delete 
        # Command to synchronize the current directory (.) with the specified S3 bucket
        # 's3://portfolio-website' is the S3 bucket name
        # '--delete' ensures that files in the S3 bucket not present locally are removed
